apiVersion: v1
kind: ConfigMap
metadata:
  name: renterd
data:
  renterd.yml: |
    bus:
      gatewayAddr: "0.0.0.0:{{ .Values.service.bus.port }}"
    s3:
      enabled: {{ .Values.renterd.s3.enabled }}
  entrypoint.sh: |
    #!/bin/sh
    exec renterd -http=':{{ .Values.service.http.port }}' -s3.address=':{{ .Values.service.s3.port }}' "$@"