apiVersion: v1
kind: ConfigMap
metadata:
  name: renterd
data:
  renterd.bus.yml: |
    # Managed by Helm - configmap/renterd/renterd.bus.yml
    bus:
      gatewayAddr: "0.0.0.0:{{ .Values.service.bus.port }}"
      {{ with .Values.renterd.bus.config }}
      {{ . | toYaml | nindent 6 }}
      {{- end }}
    s3:
      enabled: {{ .Values.renterd.s3.enabled }}
  renterd.worker.yml: |
    # Managed by Helm - configmap/renterd/renterd.worker.yml
    s3:
      enabled: {{ .Values.renterd.s3.enabled }}
    {{ with .Values.renterd.workers.config }}
    worker: {{ . | toYaml | nindent 6 }}
    {{- end }}
  renterd.autopilot.yml: |
    # Managed by Helm - configmap/renterd/renterd.autopilot.yml
    {{ with .Values.renterd.autopilot.config }}
    autopilot: {{ . | toYaml | nindent 6 }}
    {{- end }}
  entrypoint.sh: |
    #!/bin/sh
    # Managed by Helm - configmap/renterd/entrypoint.sh
    exec renterd -http=':{{ .Values.service.http.port }}' -s3.address=':{{ .Values.service.s3.port }}' "$@"