apiVersion: v1
kind: Service
metadata:
  name: renterd-bus
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.bus.port }}
      targetPort: {{ .Values.service.bus.port }}
      protocol: TCP
      name: bus
  selector:
    {{- include "renterd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: bus
---
apiVersion: v1
kind: Service
metadata:
  name: renterd-autopilot
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "renterd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: autopilot
---
apiVersion: v1
kind: Service
metadata:
  name: renterd-worker
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  publishNotReadyAddresses: true
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.port }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.bus.port }}
      targetPort: {{ .Values.service.bus.port }}
      protocol: TCP
      name: bus
    - port: {{ .Values.service.s3.port }}
      targetPort: {{ .Values.service.s3.port }}
      protocol: TCP
      name: s3
  selector:
    {{- include "renterd.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: worker