apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: renterd-worker
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  serviceName: "renterd-worker"
  replicas: {{ .Values.renterd.workers.replicas }}
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "renterd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "renterd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
      annotations:
        checksum/configmap-renterd: {{ include (print $.Template.BasePath "/configmaps/renterd.yaml") . | sha256sum }}
        checksum/configmap-renterd-worker: {{ include (print $.Template.BasePath "/configmaps/renterd-worker.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: {{ .Values.renterd.workers.automountServiceAccountToken }}
      enableServiceLinks: {{ .Values.renterd.workers.enableServiceLinks }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: wait-for
          image: ghcr.io/patrickdappollonio/wait-for:v1.0.0
          args:
            - --verbose
            # Wait for bus before starting workers
            - --host="renterd-bus:{{$.Values.service.http.port}}"
      containers:
        - name: renterd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bus
              containerPort: {{ .Values.service.bus.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/data"
              name: renterd-data-emptydir
            - mountPath: "/data/renterd.yml"
              name: renterd-worker-config
              subPath: "renterd.yml"
            - mountPath: "/entrypoint.sh"
              name: renterd-config
              subPath: "entrypoint.sh"
          env:
            - name: RENTERD_WORKER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RENTERD_AUTOPILOT_ENABLED
              value: "false"
            - name: RENTERD_WORKER_ENABLED
              value: "true"
            - name: RENTERD_BUS_REMOTE_ADDR
              value: {{ include "renterd.busAddr" . | quote }}
          envFrom:
            - secretRef:
                name: {{ .Values.renterd.secretName | quote }}
          resources:
            {{- toYaml .Values.renterd.workers.resources | nindent 12 }}
          {{- if .Values.renterd.workers.nodeSelector }}
          nodeSelector: {{- .Values.renterd.workers.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.renterd.workers.affinity }}
          affinity: {{- .Values.renterd.workers.affinity | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.renterd.workers.tolerations }}
          tolerations: {{- .Values.renterd.workers.tolerations | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.renterd.workers.topologySpreadConstraints }}
          topologySpreadConstraints: {{- .Values.renterd.workers.topologySpreadConstraints | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: renterd-config
          configMap:
            name: renterd
            defaultMode: 0755
        - name: renterd-worker-config
          configMap:
            name: renterd-worker
            defaultMode: 0755
        - name: renterd-data-emptydir
          emptyDir:
            medium: "Memory"
            sizeLimit: 128Mi