apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: renterd-bus
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
    app.kubernetes.io/component: bus
spec:
  serviceName: "renterd-bus"
  replicas: 1
  selector:
    matchLabels:
      {{- include "renterd.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: bus
  template:
    metadata:
      labels:
        {{- include "renterd.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: bus
      annotations:
        checksum/configmap-renterd: {{ include (print $.Template.BasePath "/configmaps/renterd.yaml") . | sha256sum }}
        checksum/configmap-renterd-bus: {{ include (print $.Template.BasePath "/configmaps/renterd-bus.yaml") . | sha256sum }}
        checksum/secret-renterd-mysql: {{ include (print $.Template.BasePath "/secrets/renterd-mysql.yaml") . | sha256sum }}
    spec:
      automountServiceAccountToken: {{ .Values.bus.automountServiceAccountToken }}
      enableServiceLinks: {{ .Values.bus.enableServiceLinks }}
      {{- with .Values.bus.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{ if .Values.databaseSecretName }}
      initContainers:
        - name: wait-for
          image: artur9010/wait-for:v1.0.0
          args:
            - --verbose
            - --timeout=60s
            # Wait for db before starting bus
            - --host="$(RENTERD_DB_URI)"
          envFrom:
            - secretRef:
                name: {{ .Values.databaseSecretName | quote }}
      {{ end }}
      containers:
        - name: renterd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: bus
              containerPort: {{ .Values.service.bus.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - mountPath: "/data"
              name: renterd-bus-data
            - mountPath: "/data/renterd.yml"
              name: renterd-bus-config
              subPath: "renterd.yml"
            - mountPath: "/entrypoint.sh"
              name: renterd-config
              subPath: "entrypoint.sh"
          envFrom:
            - secretRef:
                name: {{ .Values.secretName | quote }}
            {{ if .Values.databaseSecretName }}
            - secretRef:
                name: {{ .Values.databaseSecretName | quote }}
            {{ end }}
          env:
            - name: RENTERD_AUTOPILOT_ENABLED
              value: "false"
            - name: RENTERD_WORKER_ENABLED
              value: "false"
          resources:
            {{- toYaml .Values.bus.resources | nindent 12 }}
          {{- if .Values.bus.nodeSelector }}
          nodeSelector: {{- .Values.bus.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.bus.affinity }}
          affinity: {{- .Values.bus.affinity | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.bus.tolerations }}
          tolerations: {{- .Values.bus.tolerations | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.workers.topologySpreadConstraints }}
          topologySpreadConstraints: {{- .Values.workers.topologySpreadConstraints | toYaml | nindent 12 }}
          {{- end }}
      volumes:
        - name: renterd-config
          configMap:
            name: renterd
            defaultMode: 0755
        - name: renterd-bus-config
          configMap:
            name: renterd-bus
            defaultMode: 0755
  volumeClaimTemplates:
    - metadata:
        name: renterd-bus-data
      spec:
        {{- toYaml .Values.bus.volume | nindent 8 }}
