{{ if .Values.renterd.bus.vpa.enabled -}}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: renterd-bus
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: renterd-bus
{{ end }}
---
{{ if .Values.renterd.autopilot.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: renterd-autopilot
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: renterd-autopilot
{{ end }}
---
{{ if .Values.renterd.workers.vpa.enabled }}
apiVersion: "autoscaling.k8s.io/v1"
kind: VerticalPodAutoscaler
metadata:
  name: renterd-worker
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: StatefulSet
    name: renterd-worker
{{ end }}