apiVersion: v1
kind: ConfigMap
metadata:
  name: renterd-worker
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
data:
  renterd.yml: |
    # Managed by Helm - configmap/renterd-worker/renterd.yml
    s3:
      enabled: {{ .Values.s3.enabled }}
    {{ with .Values.workers.config }}
    worker: {{ . | toYaml | nindent 6 }}
    {{- end }}
