apiVersion: v1
kind: ConfigMap
metadata:
  name: renterd-bus
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
data:
  renterd.yml: |
    # Managed by Helm - configmap/renterd-bus/renterd.yml
    bus:
      gatewayAddr: "0.0.0.0:{{ .Values.service.bus.port }}"
      {{ with .Values.bus.config }}
      {{ . | toYaml | nindent 6 }}
      {{- end }}
    s3:
      enabled: {{ .Values.s3.enabled }}