apiVersion: v1
kind: ConfigMap
metadata:
  name: renterd-bus
data:
  renterd.yml: |
    # Managed by Helm - configmap/renterd-bus/renterd.yml
    bus:
      gatewayAddr: "0.0.0.0:{{ .Values.service.bus.port }}"
      {{ with .Values.renterd.bus.config }}
      {{ . | toYaml | nindent 6 }}
      {{- end }}
    s3:
      enabled: {{ .Values.renterd.s3.enabled }}