{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | quote }}
  labels:
    {{- include "s3d.labels" . | nindent 4 }}
type: Opaque
stringData:
  S3D_RECOVERY_PHRASE: {{ .Values.secretContent.S3D_RECOVERY_PHRASE | quote }}
{{- end }}