apiVersion: v1
kind: Service
metadata:
  name: s3d
  labels:
    {{- include "s3d.labels" . | nindent 4 }}
    app.kubernetes.io/component: s3
  {{- with .Values.service.s3.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.s3.type }}
  ports:
    - port: {{ .Values.service.s3.port }}
      targetPort: s3
      protocol: TCP
      name: s3
  selector:
    {{- include "s3d.selectorLabels" . | nindent 4 }}