{{- if .Values.autofaucet.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renterd-testnet-faucet-claim
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
spec:
  schedule: "{{.Values.autofaucet.cron}}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl
            image: quay.io/curl/curl:latest
            imagePullPolicy: IfNotPresent
            command:
            - curl
            - "https://faucet.zen.sia.tech/api/request"
            - --data-raw
            - '{"unlockHash":"{{.Values.autofaucet.address}}","amount":"{{.Values.autofaucet.amount}}"}'
          restartPolicy: {{.Values.autofaucet.restartPolicy}}
{{- end }}