apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  labels:
    app.kubernetes.io/name: cloudflared
spec:
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: cloudflared