apiVersion: v2
name: renterd
description: Sia renterd helm chart
type: application
version: 1.0.0
appVersion: "1.0.0"
icon: https://i.imgur.com/pWg0PRK.png
dependencies:
  - name: mysql
    version: 9.14.4
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled