apiVersion: v2
name: renterd
description: Sia renterd helm chart
type: application
version: 1.0.1
appVersion: "1.0.0"
icon: https://i.imgur.com/pWg0PRK.png
keywords:
- storage
- distributed
- blockchain
- sia
- renter
- s3
- webui
dependencies:
  - name: mysql
    version: 9.16.0
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled