apiVersion: v2
name: renterd
description: Sia renterd helm chart
type: application
version: 1.1.3
appVersion: "1.0.6"
icon: https://i.imgur.com/pWg0PRK.png
keywords:
- storage
- distributed
- blockchain
- sia
- renter
- s3
- webui
dependencies:
  - name: mysql
    version: 10.1.1
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled