apiVersion: v2
name: renterd
description: Sia renterd helm chart
type: application
version: 1.1.0
appVersion: "1.0.5"
icon: https://i.imgur.com/pWg0PRK.png
keywords:
- storage
- distributed
- blockchain
- sia
- renter
- s3
- webui
dependencies:
  - name: mysql
    version: 9.23.0
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled