{{ if .Values.mysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: renterd-mysql
type: Opaque
data:
  RENTERD_DB_URI: {{ "mysql:3306" | b64enc | quote }}
  RENTERD_DB_USER: {{ .Values.mysql.auth.username | b64enc | quote }}
  RENTERD_DB_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  RENTERD_DB_NAME: {{ .Values.mysql.auth.database | b64enc | quote }}
  RENTERD_DB_METRICS_NAME: {{ .Values.mysql.auth.databaseMetrics | b64enc | quote }}
{{ end }}