{{ if .Values.createDatabaseSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseSecretName | quote }}
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.databaseSecretContent | toYaml | nindent 2 }}
{{ end }}