apiVersion: v1
kind: Secret
metadata:
  name: renterd-env
type: Opaque
data:
  RENTERD_SEED: {{ .Values.renterd.seed | b64enc | quote }}
  RENTERD_API_PASSWORD: {{ .Values.renterd.api.password | b64enc | quote }}
  RENTERD_BUS_API_PASSWORD: {{ .Values.renterd.api.password | b64enc | quote }}
  RENTERD_WORKER_API_PASSWORD: {{ .Values.renterd.api.password | b64enc | quote }}