apiVersion: v1
kind: Secret
metadata:
  name: renterd-bus-env
type: Opaque
data:
  # db is only used by bus
  {{ if .Values.mysql.enabled }}
  RENTERD_DB_URI: {{ "mysql:3306" | b64enc | quote }}
  RENTERD_DB_USER: {{ .Values.mysql.auth.username | b64enc | quote }}
  RENTERD_DB_PASSWORD: {{ .Values.mysql.auth.password | b64enc | quote }}
  RENTERD_DB_NAME: {{ .Values.mysql.auth.database | b64enc | quote }}
  RENTERD_DB_METRICS_NAME: {{ .Values.mysql.auth.databaseMetrics | b64enc | quote }}
  {{ else }}
  RENTERD_DB_URI: {{ .Values.mysqlExternal.address | b64enc | quote }}
  RENTERD_DB_USER: {{ .Values.mysqlExternal.username | b64enc | quote }}
  RENTERD_DB_PASSWORD: {{ .Values.mysqlExternal.password | b64enc | quote }}
  RENTERD_DB_NAME: {{ .Values.mysqlExternal.database | b64enc | quote }}
  RENTERD_DB_METRICS_NAME: {{ .Values.mysqlExternal.databaseMetrics | b64enc | quote }}
  {{ end }}