{{ if or .Values.mysql.enabled .Values.createDatabaseSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseSecretName | quote }}
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.createDatabaseSecret }}
    {{ .Values.databaseSecretContent | toYaml | nindent 2 }}
  {{- else }}
  RENTERD_DB_URI: "mysql:3306"
  RENTERD_DB_USER: {{ .Values.mysql.auth.username | quote }}
  RENTERD_DB_PASSWORD: {{ .Values.mysql.auth.password | quote }}
  RENTERD_DB_NAME: {{ .Values.mysql.auth.database | quote }}
  RENTERD_DB_METRICS_NAME: {{ .Values.mysql.auth.databaseMetrics | quote }}
  {{- end }}
{{ end }}