token: ""
ingress:
  # This rule matches any traffic which didn't match a previous rule, and responds with built-in into chart nginx ingress.
  - service: nginx-cloudflared-controller:80

cloudflared:
  # Available values: DaemonSet, Deployment
  type: DaemonSet
  replicaCount: 1 # only for Deployment
  image:
    repository: cloudflare/cloudflared
    tag: "2025.7.0@sha256:803b17adb5326a38ce397b9c9f374289ad290ee5526d204b5879a1423b6f5c3e"
    pullPolicy: IfNotPresent
  nodeSelector: {}
  tolerations: []
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 256Mi

ingress-nginx:
  fullnameOverride: nginx-cloudflared
  controller:
    kind: DaemonSet
    ingressClassByName: true
    ingressClass: nginx-cloudflared
    ingressClassResource:
      name: nginx-cloudflared
      enabled: true
      controllerValue: "k8s.io/ingress-nginx-cloudflared"
    service:
      enabled: true
      type: ClusterIP
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      forwarded-for-header: "CF-Connecting-IP"