token: ""
ingress:
  # This rule matches any traffic which didn't match a previous rule, and responds with built-in into chart nginx ingress.
  - service: nginx-cloudflared-controller:80

ingress-nginx:
  enabled: true
  fullnameOverride: nginx-cloudflared
  controller:
    kind: DaemonSet
    ingressClassByName: true
    ingressClass: nginx-cloudflared
    ingressClassResource:
      name: nginx-cloudflared
      enabled: true
      controllerValue: "k8s.io/ingress-nginx-cloudflared"
    service:
      enabled: true
      type: ClusterIP
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 100m
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      forwarded-for-header: "CF-Connecting-IP"