apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.name | quote }}
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
spec:
  {{- toYaml .Values.storage.spec | nindent 2 }}