{{ if .Values.autopilot.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: renterd-autopilot
  labels:
    {{- include "renterd.labels" . | nindent 4 }}
data:
  renterd.yml: |
    # Managed by Helm - configmap/renterd-autopilot/renterd.yml
    {{ with .Values.autopilot.config }}
    autopilot: {{ . | toYaml | nindent 6 }}
    {{- end }}
    # TODO: dirty bugfix - renterd excepts at least one section in config
    s3:
      enabled: {{ .Values.s3.enabled }}
{{ end }}