token: ENC[AES256_GCM,data:pODtJbWPggU/2DXgqZ36PvpC41Cw4bN1lTEErNwGQ8s80yIfCvyIkLnkAKydQjMhpv0eGoUtxwE/3+CUzJFkSi4r7bmq5GL/45eLeuwXW6wC26H4jWul7e1UTMeYjgaFw5gP1lojxdD4zcNcmHxExeNaPl4wUA/3M3hw26/NfnugcymhY/gqAzV0ObzX8wKIp15i9vgD3Vjdsqc/e0l6T/e9U0dzHkREG+aDhsiL/YvLUnKRn6Wx0A==,iv:xLIMx2vYhx6Z3XA9gzu5d9MJoz80QK9cXCAGN527CeM=,tag:MH4aNuEkC1U8y1y9FW2ziA==,type:str]
sops:
    kms:
        - arn: arn:aws:kms:eu-central-1:860839673359:key/7b008fda-9722-4188-9bcf-e80472075aba
          created_at: "2025-05-23T14:14:17Z"
          enc: AQICAHgFsjM7zBxq2zTdpO8UziMvuy8C01waulUFTmos9R7n6AHaru1fNXN8M8VZbucnNrB+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM57fS3pzEUdiVkvDLAgEQgDuqtWubb5E+bx5AozNqP1PaxQt5os9J0BZY3pnBSwrcvc1lnluNb18B+uP4DQva+/oYZ+gfhOyO1I5f4Q==
          aws_profile: ""
    lastmodified: "2025-08-26T18:37:33Z"
    mac: ENC[AES256_GCM,data:/920lGWIyJpXWjXajRT1/JW9+Qz8km0w9CeusA/BA0s1ntn07mCVrsYpjmqwDDCoMXoq1qnJnSLviihAaC2l6StEzxFXWevP2TpipQV2ZT+LODXcSROP7CXH/KF50UMICvzLocEaH+PQlU9knQbv2oE8ZnMMjEbPLrPkjay/32o=,iv:Gp+POoDpBnYrzozt67xZKfQX3ebmVGTW67oK/+9xHPY=,tag:73l7yyz9mKYKftUa+RUyoQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
