apiVersion: v1
kind: Service
metadata:
  name: cloudflared
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 2000
      targetPort: 2000
      protocol: TCP
      name: metrics
  selector:
    {{- include "cloudflared.selectorLabels" . | nindent 4 }}