name: Renovate

on:
  schedule:
    - cron: '0 * * * *'  # Run hourly
  workflow_dispatch:     # Allow manual triggers

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Renovate
        uses: renovatebot/github-action@v43.0.9
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          LOG_LEVEL: debug
          RENOVATE_REPOSITORIES: ${{ github.repository }}
      # todo: run build.sh